dict_currency_get = {
    'EUR': ['Albania 🇦🇱', 'Andorra 🇦🇩', 'Austria 🇦🇹', 'Belgium 🇧🇪', 'Bosnia and Herzegovina 🇧🇦',
            'Bulgaria 🇧🇬', 'Croatia 🇭🇷', 'Cyprus 🇨🇾', 'Czech Republic 🇨🇿', 'Denmark 🇩🇰',
            'Estonia 🇪🇪', 'France 🇫🇷', 'Finland 🇫🇮', 'Georgia 🇬🇪', 'Hungary 🇭🇺', 'United Kingdom 🇬🇧',
            'Iceland 🇮🇸', 'Ireland 🇮🇪', 'Italy 🇮🇹', 'Latvia 🇱🇻', 'Lithuania 🇱🇹', 'Luxembourg 🇱🇺',
            'Macedonia 🇲🇰', 'Malta 🇲🇹', 'Montenegro 🇲🇪', 'Netherlands 🇳🇱', 'Poland 🇵🇱',
            'Portugal 🇵🇹', 'Serbia 🇷🇸', 'Slovakia 🇸🇰', 'Slovenia 🇸🇮', 'Spain 🇪🇸', 'Switzerland 🇨🇭'],
    'USD': ['Armenia 🇦🇲', 'Azerbaijan 🇦🇿', 'Ecuador 🇪🇨', 'El Salvador 🇸🇻', 'Malaysia 🇲🇾', ],
    'RUB': ['Russia 🇷🇺'],
    'DZD': ['Algeria 🇩🇿'],
    'AMD': ['Armenia 🇦🇲'],
    'AZN': ['Azerbaijan 🇦🇿'],
    'BDT': ['Bangladesh 🇧🇩'],
    'BYN': ['Belarus 🇧🇾'],
    'BRL': ['Brazil 🇧🇷'],
    'BGN': ['Bulgaria 🇧🇬'],
    'CAD': ['Canada 🇨🇦'],
    'CNY': ['China 🇨🇳'],
    'CZK': ['Czech Republic 🇨🇿'],
    'EGP': ['Egypt 🇪🇬'],
    'GEL': ['Georgia 🇬🇪'],
    'HKD': ['Hong Kong'],
    'HUF': ['Hungary 🇭🇺'],
    'INR': ['India 🇮🇳'],
    'IDR': 'Indonesia',
    'ILS': ['Israel 🇮🇱'],
    'JPY': ['Japan 🇯🇵'],
    'KZT': ['Kazakhstan 🇰🇿'],
    'KGS': ['Kyrgyzstan'],
    'LBP': ['Lebanon 🇱🇧'],
    'MYR': ['Malaysia 🇲🇾'],
    'MXN': ['Mexico 🇲🇽'],
    'MDL': ['Moldova 🇲🇩'],
    'MAD': ['Morocco 🇲🇦'],
    'NZD': ['New Zealand 🇳🇿'],
    'PKR': ['Pakistan 🇵🇰'],
    'PLN': ['Poland 🇵🇱'],
    'RON': ['Romania 🇷🇴'],
    'SAR': ['Saudi Arabia 🇸🇦'],
    'RSD': ['Serbia 🇷🇸'],
    'KRW': ['South Korea 🇰🇷'],
    'TJS': ['Tajikistan 🇹🇯'],
    'THB': ['Thailand 🇹🇭'],
    'TRY': ['Turkey 🇹🇷'],
    'AED': ['UAE 🇦🇪'],
    'UAH': ['Ukraine 🇺🇦'],
    'UZS': ['Uzbekistan 🇺🇿'],
    'VND': ['Vietnam 🇻🇳'],
}

list_currency_get = ['EUR', 'USD', 'RUB', 'DZD', 'AMD', 'AZN', 'BDT', 'BYN', 'BRL', 'BGN', 'CAD', 'CNY', 'CZK', 'EGP', 'GEL', 'HKD', 'HUF', 'INR', 'IDR', 'ILS', 'JPY', 'KZT', 'KGS', 'LBP', 'MYR', 'MXN', 'MDL', 'MAD', 'NZD', 'PKR', 'PLN', 'RON', 'SAR', 'RSD', 'KRW', 'TJS', 'THB', 'TRY', 'AED', 'UAH', 'UZS', 'VND']
